### ISSUE TITLE
Sparkline does not generate

### ISSUE THREAD

**Issue by wesoudshoorn** [Volorf/Sparkliner#1]
Followed all the instructions multiple times. When selecting multiple squares it throws an error saying I only need to select one rectangle. This makes me conclude the plugin is properly installed. 

If I only select one, nothing happens at all.

**Details**
- Version 3.6.1 (26313)
- Other plugins installed: Panels (invisionlabs)
- OSX 10.11.3 (15D21)

**Comment by Volorf** [comment]
Hi!

Thanks for your report. I found the mistake. When you create sparkline you have to surely put your rectangle on an artboard. Require. In the near future I will fix it :)

**Comment by wesoudshoorn** [comment]
Hi @Volorf, I am still not getting this to work. Even inside an artboard.

**Comment by Tele-Pet** [comment]
I'm also unable to get this working.  I've tried having the `example.json` saved in the same folder as the Sketch file, but that doesn't have any effect.  This looks like a really cool plugin.  Looking forward to learning how to get it working!
- Version 3.8.2 (29753)
- 10.11.4 (15E65)

**Comment by wesoudshoorn** [comment]
@Volorf Thanks for fixing this! This little unknown plugin is making people's day better 💯

**Comment by Tele-Pet** [comment]
It's working for me now.  @Volorf Thanks very much for this amazing plugin!
